project:
  name: "breast_cancer_classification"
  author: "student"

data:
  raw_path: "data/raw/wdbc.data"
  train_path: "data/processed/train.csv"
  test_path: "data/processed/test.csv"
  # Оскільки файл без заголовків, вказуємо імена колонок вручну (спрощено для 30 ознак)
  target_col: "diagnosis"
  id_col: "id"
  # Параметри розділення
  split:
    test_size: 0.2
    random_state: 42
    stratify: True  # Важливо для дисбалансу класів

model:
  type: "LogisticRegression" # Почнемо з простого baseline
  params:
    C: 1.0
    solver: "liblinear"
    random_state: 42

mlflow:
  experiment_name: "Breast_Cancer_Experiments"
  tracking_uri: "mlruns" # Локально